#
name: Create and publish a Image for the PR

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  pull_request:
    types: closed
    paths:
      - 'src/**'
      - 'Dockerfile'
  workflow_dispatch:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: thecfu/scraparr-dev

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      packages: write

    steps:
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Remove Docker image
        id: remove
        run: docker image rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr${{ github.event.pull_request.number }}
